currentstate: online
datetimeformat: '%Y-%m-%d %H:%M:%S'
eventdate: '2023-02-18'
eventid: 4b255347-bd8f-47f4-8cd2-7d3d7ab95cf9
hosts:
- google.com
- bbc.co.uk
lastcheck: '2023-02-18 18:10:09'
pollfreq: 10
speedtestfreq: 30
