currentstate: online
datetimeformat: '%m-%d-%Y %H:%M:%S'
eventdate: '2023-02-14'
eventid: f3794bfb-a2ff-4622-ac4e-45ae7296b649
hosts:
- google.com
- bbc.co.uk
lastcheck: 02-14-2023 16:05:08
pollfreq: 10
