connectionmonitorjobstatus: run
datetimeformat: '%Y-%m-%d %H:%M:%S'
defaultinterface: en0
hosts:
- google.com
- bbc.co.uk
logginglevel: INFO
pollfreq: 10
speedtestfreq: 60
speedtestjobstatus: pause
speedtestserverid: Any
tracetargethost: 8.8.8.8
