currentstate: online
datetimeformat: '%Y-%m-%d %H:%M:%S'
eventdate: '2023-02-19'
eventid: 0c0ad36a-89c5-4cb8-b269-aa23e6fce2bd
hosts:
- google.com
- bbc.co.uk
lastcheck: '2023-02-19 15:53:54'
pollfreq: 10
speedtestfreq: 30
