checknetconfigjobstatus: run
connectionmonitorjobstatus: run
datetimeformat: '%Y-%m-%d %H:%M:%S'
defaultinterface: en0
hosts:
- - google.com
  - inet
- - bbc.co.uk
  - inet
logginglevel: INFO
netconfigtestfreq: 86400
pollfreq: 10
speedtestfreq: 60
speedtestjobstatus: run
speedtestserverid: '18531'
tracetargethost: 8.8.8.8
