services:
  redis:
    image: redis
    container_name: redis
    networks:
      - ispmonitor
    restart: always
    ports:
      - 6379:6379
    volumes:
      - redis_data:/data
  ispmonitor:
    image: simonsecuritypedant/ispmonitor:1.1
    container_name: ispmonitor
    depends_on:
      - redis
    networks:
      - ispmonitor
    ports:
      - 8000:8000
    volumes:
      - logs:/usr/src/app/logs
      - events:/usr/src/app/events
      - data:/usr/src/app/graphdata
      - config:/usr/src/app/config

volumes:
  redis_data: {}
  logs: {}
  events: {}
  data: {}
  config: {}

networks:
  ispmonitor: {}
