services:
  mongo:
    image: mongo
    container_name: mongo
    networks:
      - ispmonitor
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 123qweQWE
    volumes:
      - mongo_data:/data/db
  redis:
    image: redis
    container_name: redis
    networks:
      - ispmonitor
    restart: always
    ports:
      - 6379:6379
    volumes:
      - redis_data:/data
  ispmonitor:
    image: simonsecuritypedant/ispmonitor:1.4
    container_name: ispmonitor
    depends_on:
      - redis
    networks:
      - ispmonitor
    ports:
      - 8000:8000
    volumes:
      - data:/usr/src/app/data/
      - config:/usr/src/app/config

volumes:
  redis_data: {}
  data: {}
  config: {}
  mongo_data: {}

networks:
  ispmonitor: {}
