checknetconfigjobstatus: run
connectionmonitorjobstatus: run
datetimeformat: '%Y-%m-%d %H:%M:%S'
defaultinterface: en0
hosts:
- - google.com
  - inet
- - bbc.co.uk
  - inet
logginglevel: INFO
netconfigtestfreq: 86400
pollamount: 2
pollfreq: 10
speedtestfreq: 7200
speedtestjobstatus: run
speedtestserverid: '18531'
tracetargethost: 1.1.1.1
mongoDbPort: 27018
mongoDbHost: localhost
mongoDbUser: root
mongoDbPass: 123qweQWE
mongoDbName: ispmonitor
appSecretKey: h79h4n93q4tny34c7y9nqn3pc3epy