checknetconfigjobstatus: run
connectionmonitorjobstatus: run
datetimeformat: '%Y-%m-%d %H:%M:%S'
defaultinterface: en0
hosts:
- - google.com
  - inet
- - bbc.co.uk
  - inet
logginglevel: WARNING
netconfigtestfreq: 86400
pollamount: 2
pollfreq: 10
redis_host: localhost
redis_port: 6379
speedtestfreq: 7200
speedtestjobstatus: run
speedtestserverid: '18531'
tracetargethost: 8.8.8.8
